name: 📝 Add New Entry to Database
description: Use this form to add a row to data/data.csv
title: " Data Entry "
labels: ["data-entry"]
body:
  - type: markdown
    attributes:
      value: "### 📝 Resource Details"
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to source
  - type: checkboxes
    id: categories
    attributes:
      label: Categories
      options:
        - label: webpage
        - label: course
        - label: video
        - label: article
        - label: document
        - label: practical guides
        - label: meeting
  - type: checkboxes
    id: knowledge
    attributes:
      label: Knowledge level
      description: Select one or more levels.
      options:
        - label: any level
        - label: beginner
        - label: intermediate
        - label: advanced
  - type: checkboxes
    id: time
    attributes:
      label: Time needed
      description: Select one or more options.
      options:
        - label: few hours
        - label: one day
        - label: few days
        - label: one week
        - label: few weeks
        - label: one month
        - label: few months
        - label: self-paced
  - type: checkboxes
    id: language
    attributes:
      label: Language
      description: Select one or more languages.
      options:
        - label: EN
        - label: CZ
        - label: DE
        - label: FR
  - type: checkboxes
    id: keywords
    attributes:
      label: Keywords
      options:
        - label: Data Steward Training
        - label: open science
        - label: data
        - label: database
        - label: repositories
        - label: licensing
        - label: good practices
        - label: bad practices
        - label: RDM
        - label: DMP
        - label: FAIR
        - label: HE
        - label: GAČR
        - label: other
  - type: textarea
    id: information
    attributes:
      label: Information
