name: 📝 Add New Entry to Database
description: Use this form to add a row to data/data.csv
title: "[Data Entry]: "
labels: ["data-entry"]
body:
  - type: input
    id: input_title
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    id: input_link
    attributes:
      label: Link to source
  - type: checkboxes
    id: input_categories
    attributes:
      label: Categories (Select all that apply)
      options:
        - label: webpage
        - label: course
        - label: video
        - label: article
        - label: document
        - label: practical guides
        - label: meeting
  - type: input
    id: input_knowledge
    attributes:
      label: Knowledge level
  - type: input
    id: input_time
    attributes:
      label: Time needed
  - type: input
    id: input_language
    attributes:
      label: Language
  - type: checkboxes
    id: input_keywords
    attributes:
      label: Keywords / Funding Agency
      options:
        - label: Data Steward Training
        - label: open science
        - label: data
        - label: database
        - label: repositories
        - label: licensing
        - label: good practices
        - label: bad practices
        - label: RDM
        - label: DMP
        - label: FAIR
        - label: HE
        - label: GAČR
        - label: other
  - type: textarea
    id: input_info
    attributes:
      label: Information
