name: 📝 Add New Entry to Database
description: Use this form to add a row to data/data.csv
title: " Data Entry "
labels: ["data-entry"]
body:
  - type: markdown
    attributes:
      value: "### Please fill in the resource details below."
  - type: input
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    attributes:
      label: Link to source
  - type: checkboxes
    attributes:
      label: Categories
      options:
        - label: webpage
        - label: course
        - label: video
        - label: article
        - label: document
        - label: practical guides
        - label: meeting
  - type: input
    attributes:
      label: Knowledge level
  - type: input
    attributes:
      label: Time needed
  - type: input
    attributes:
      label: Language
  - type: checkboxes
    attributes:
      label: Keywords
      options:
        - label: Data Steward Training
        - label: open science
        - label: data
        - label: database
        - label: repositories
        - label: licensing
        - label: good practices
        - label: bad practices
        - label: RDM
        - label: DMP
        - label: FAIR
        - label: HE
        - label: GAČR
        - label: other
  - type: textarea
    attributes:
      label: Information
