name: 📝 Add New Entry to Database
description: Use this form to add a row to data/data.csv
title: " Data Entry "
labels: ["data-entry"]
body:
  - type: markdown
    attributes:
      value: "### 📝 Resource Details"
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to source
  - type: checkboxes
    id: categories
    attributes:
      label: Categories
      options:
        - label: webpage
        - label: course
        - label: video
        - label: article
        - label: document
        - label: practical guides
        - label: meeting
  - type: checkboxes
    id: knowledge_level
    attributes:
      label: Knowledge level
      options:
        - label: any level
        - label: beginner
        - label: intermediate
        - label: advanced
  - type: dropdown
    id: duration_choice
    attributes:
      label: Time needed (Duration)
      options:
        - "few hours"
        - "few days"
        - "few weeks"
        - "few months"
  - type: checkboxes
    id: self_paced_choice
    attributes:
      label: Format
      options:
        - label: self-paced
  - type: checkboxes
    id: language_choice
    attributes:
      label: Language
      options:
        - label: EN
        - label: CZ
        - label: DE
        - label: FR
  - type: checkboxes
    id: keywords
    attributes:
      label: Keywords
      options:
        - label: Data Steward Training
        - label: open science
        - label: data
        - label: database
        - label: repositories
        - label: licensing
        - label: good practices
        - label: bad practices
        - label: RDM
        - label: DMP
        - label: FAIR
        - label: HE
        - label: GAČR
        - label: other
  - type: textarea
    id: information
    attributes:
      label: Information
