name: 📝 Add New Entry to Database
description: Use this form to add a row to data/data.csv
title: "[Data Entry]: "
labels: ["data-entry"]
body:
  - type: markdown
    attributes:
      value: "Please fill in the details below. The top 'Add a title' field is for the Issue name, while the 'Title' field below is for the resource name."
  - type: input
    id: title_field
    attributes:
      label: Title
      placeholder: "e.g., Introduction to RDM"
    validations:
      required: true
  - type: input
    id: link_field
    attributes:
      label: Link to source
  - type: checkboxes
    id: cat_field
    attributes:
      label: Categories (Select all that apply)
      options:
        - label: webpage
        - label: course
        - label: video
        - label: article
        - label: document
        - label: practical guides
        - label: meeting
  - type: input
    id: know_field
    attributes:
      label: Knowledge level
  - type: input
    id: time_field
    attributes:
      label: Time needed
  - type: input
    id: lang_field
    attributes:
      label: Language
  - type: checkboxes
    id: key_field
    attributes:
      label: Keywords / Funding Agency
      options:
        - label: Data Steward Training
        - label: open science
        - label: data
        - label: database
        - label: repositories
        - label: licensing
        - label: good practices
        - label: bad practices
        - label: RDM
        - label: DMP
        - label: FAIR
        - label: HE
        - label: GAČR
        - label: other
  - type: textarea
    id: info_field
    attributes:
      label: Information
