name: 📝 Add New Entry to Database
description: Fill out this form to add a new resource to the data/data.csv file.
title: "[Data Entry]: "
labels: ["data-entry"]
body:
  - type: markdown
    attributes:
      value: |
        ### Core Information
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: e.g., Data Management Basics
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to source
      placeholder: https://...

  - type: dropdown
    id: categories
    attributes:
      label: Categories
      options:
        - Data Steward Training
        - Open Science
        - Both
        - Other

  - type: input
    id: knowledge_level
    attributes:
      label: Knowledge level
      placeholder: e.g., Beginner

  - type: input
    id: time_needed
    attributes:
      label: Time needed
      placeholder: e.g., 45 mins

  - type: input
    id: language
    attributes:
      label: Language
      placeholder: e.g., English

  - type: checkboxes
    id: keywords
    attributes:
      label: Keywords / Funding Agency
      options:
        - label: data
        - label: database
        - label: repositories
        - label: licensing
        - label: good practices
        - label: bad practices
        - label: RDM
        - label: DMP
        - label: FAIR
        - label: HE
        - label: GAČR
        - label: other

  - type: textarea
    id: information
    attributes:
      label: Information
      placeholder: Additional description or notes...
